### PR TITLE
Fixed UserController security and updated club validation

### LINKED ISSUE #1598: [Club, API] Non-informative error messages appear in case of entering incorrect data into request body
**Environment:** Windows 11, Google Chrome Version 108.0.5359.125 (Official Build) (64-bit).
**Reproducible:** always.
**Build found:** last commit [5757356](https://github.com/ita-social-projects/TeachUA/commit/57573565fd58d1553fa880a969c94f7cafa0204b)

**Preconditions**
1. Postman is opened.
2. New request is added.
3. User authorized as admin.
4. Select POST HTTP method.

**Steps to reproduce**
1. Type 'https://speak-ukrainian.org.ua/dev/api/club' request URL.
2. Provide the following JSON text into request body:
{
    "ageFrom": 2,
    "ageTo": 18,
    "name": "Test Club",
    "description": "Музична школа, хор, ансамбль, гра на музичних інструментах, звукорежисерський гурток та ін.",
    "urlWeb": null,
    "urlLogo": "#",
    "urlBackground": "/static/images/club/bg_2.png",
    "urlGallery": [
        
    ],
    "workTime": null,
    "categories": [
        {
            "id": 6,
            "sortby": 25,
            "name": "Вокальна студія, музика, музичні інструменти",
            "description": "Музична школа, хор, ансамбль, гра на музичних інструментах, звукорежисерський гурток та ін.",
            "urlLogo": "/static/images/categories/music.svg",
            "backgroundColor": "#FF7A45",
            "tagBackgroundColor": "#FF7A45",
            "tagTextColor": "#fff"
        }
    ],
    "user": null,
    "center": null,
    "rating": null,
    "locations": [
        {
            "id": 517,
            "name": "club_loc_!!!",
            "address": "Одеса, вул.Балківська 42/1",
            "cityName": "Одеса",
            "districtName": "Суворовський",
            "stationName": null,
            "locationCity": {
                "id": 4,
                "name": "Одеса",
                "latitude": 46.4825,
                "longitude": 30.7233
            },
            "cityId": 4,
            "districtId": 27,
            "stationId": null,
            "clubId": 55,
            "coordinates": "string",
            "longitude": 30.705851128807083,
            "latitude": 46.48663036237369,
            "phone": "0677886867"
        }
    ],
    "isApproved": true,
    "isOnline": true,
    "feedbackCount": null,
    "contacts": null
}
3. Click the 'Send' button.

**Actual result**
A non-informative error message that the description is incorrect appeared 'description Invalid description'.
image

**Expected result**
Error message should have been more informative and in Ukrainian language.

### LINKED ISSUE #1599: [Club, API] Not obvious description for club should be provided to create a new club
**Environment:** Windows 11, Google Chrome Version 108.0.5359.125 (Official Build) (64-bit).
**Reproducible:** always.
**Build found:** last commit [5757356](https://github.com/ita-social-projects/TeachUA/commit/57573565fd58d1553fa880a969c94f7cafa0204b)

**Preconditions**
1. Postman is opened.
2. New request is added.
3. User authorized as admin.
4. Select POST HTTP method.

**Steps to reproduce**
1. Type 'https://speak-ukrainian.org.ua/dev/api/club' request URL.
2. Provide the following JSON file into the request body:
{
"ageFrom": 2,
"ageTo": 18,
"name": "Test Club",
"description": "Музична школа, хор, ансамбль, гра на музичних інструментах, звукорежисерський гурток та ін.",
"urlWeb": null,
"urlLogo": "#",
"urlBackground": "/static/images/club/bg_2.png",
"urlGallery": [

],
"workTime": null,
"categories": [
{
"id": 6,
"sortby": 25,
"name": "Вокальна студія, музика, музичні інструменти",
"description": "Музична школа, хор, ансамбль, гра на музичних інструментах, звукорежисерський гурток та ін.",
"urlLogo": "/static/images/categories/music.svg",
"backgroundColor": "#FF7A45",
"tagBackgroundColor": "#FF7A45",
"tagTextColor": "#fff"
}
],
"user": null,
"center": null,
"rating": null,
"locations": [
{
"id": 517,
"name": "club_loc_!!!",
"address": "Одеса, вул.Балківська 42/1",
"cityName": "Одеса",
"districtName": "Суворовський",
"stationName": null,
"locationCity": {
"id": 4,
"name": "Одеса",
"latitude": 46.4825,
"longitude": 30.7233
},
"cityId": 4,
"districtId": 27,
"stationId": null,
"clubId": 55,
"coordinates": "string",
"longitude": 30.705851128807083,
"latitude": 46.48663036237369,
"phone": "0677886867"
}
],
"isApproved": true,
"isOnline": true,
"feedbackCount": null,
"contacts": null
}
3. Click the 'Send' button.

**Actual result**
Error message 'description Invalid description' appeared.
image

In order for the system to accept the description it should be written in the following pattern:
{\"blocks\":[{\"key\":\"brl63\",\"text\":\"<Club_Description>\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}

**Expected result**
Club description should be written in the usual format, without any constructions in the beginning and in the end.

### PR DESCRIPTION
**Pull request by Vekeryk**
dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

### CODE REVIEW

File: src/main/java/com/softserve/teachua/dto/location/LocationProfile.java [hunk 1]
```diff
@@ -51,7 +51,7 @@ public class LocationProfile {
 
     @NotNull(message = "number cannot be null")
     @NotBlank(message = "number cannot be blank")
-    @Pattern(regexp = "0[\\d]{9}", message = "Incorrect phone Number")
+    @Pattern(regexp = "0[\\d]{9}", message = "number should contain 10 digits start with 0")
```
Comment (litvinchuck) [inline src/main/java/com/softserve/teachua/dto/location/LocationProfile.java:54]: number should contain 10 digits and start with 0?

File: src/main/java/com/softserve/teachua/dto/location/LocationResponse.java [hunk 2]
```diff
@@ -47,6 +47,6 @@ public class LocationResponse {
     private Double longitude;
     private Double latitude;
 
-    @Pattern(regexp = "0[\\d]{9}", message = "Incorrect phone number")
+    @Pattern(regexp = "0[\\d]{9}", message = "number should contain 10 digits start with 0")
```
Comment (litvinchuck) [inline src/main/java/com/softserve/teachua/dto/location/LocationResponse.java:50]: number should contain 10 digits AND start with 0?

**Review by litvinchuck — APPROVED** [review]

**Review by softservedata — APPROVED** [review]
