### PR TITLE
Fixed PATCH /api/club/{id} endpoint is not performing direct function of updating club

### LINKED ISSUE #1600: [Club, API] PATCH /api/club/{id} endpoint is not performing direct function of updating club
**Environment:** Windows 11, Google Chrome Version 108.0.5359.125 (Official Build) (64-bit).
**Reproducible:** always.
**Build found:** last commit [5757356](https://github.com/ita-social-projects/TeachUA/commit/57573565fd58d1553fa880a969c94f7cafa0204b)

**Preconditions**
1. Open Swagger UI.

**Steps to reproduce**
1. Go to 'club' section.
2. Click on '/api/club/{id}' endpoint.
3. Pay attention to the example value of the Request body.

**Actual result**
Endpoint updates the user who is assigned to the club.
image

**Expected result**
Based on the endpoint, it should update the club fields similar to the PUT method, but not all fields, only specific ones.

### PR DESCRIPTION
**Pull request by litvinchuck**
dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

### CODE REVIEW

File: src/main/java/com/softserve/teachua/controller/ClubController.java [hunk 1]
```diff
@@ -214,21 +214,37 @@ public SuccessUpdatedClub updateClub(@PathVariable Long id, @Valid @RequestBody
...
+     * Use this endpoint to update some values of club by id. The controller returns {@code SuccessUpdatedClub}.
+     *
+     * @param id
+     *            - put club id here.
+     * @param clubProfile
+     *            - Place dto with all parameters for updating existing club.
+     *
+     * @return new {@code SuccessUpdatedClub}.
+     */
+    @AllowedRoles({ RoleData.ADMIN, RoleData.USER })
```
Comment (Vekeryk) [inline src/main/java/com/softserve/teachua/controller/ClubController.java]: Only ADMIN and MANAGER can create club, so only they can put and patch

**Review by Vekeryk — CHANGES_REQUESTED** [review]

File: src/main/java/com/softserve/teachua/controller/ClubController.java (hunk 1 above)
Comment (litvinchuck) [reply src/main/java/com/softserve/teachua/controller/ClubController.java]: 👍

**Review by BNazar00 — APPROVED** [review]

**Review by Vekeryk — APPROVED** [review]

**Review by softservedata — APPROVED** [review]
